const timezones = [
    "Pacific/Midway",
    "Pacific/Honolulu",
    "Pacific/Marquesas",
    "America/Anchorage",
    "America/Los_Angeles",
    "America/Denver",
    "America/Chicago",
    "America/New_York",
    "America/Caracas",
    "America/Halifax",
    "America/St_Johns",
    "America/Buenos_Aires",
    "America/Sao_Paulo",
    "Atlantic/Cape_Verde",
    "UTC",
    "Europe/London",
    "Europe/Paris",
    "Europe/Istanbul",
    "Africa/Cairo",
    "Asia/Jerusalem",
    "Asia/Dubai",
    "Asia/Kolkata",
    "Asia/Hong_Kong",
    "Asia/Tokyo",
    "Australia/Sydney",
    "Pacific/Auckland",
  ];

  export default timezones;